import { sel, yn, num } from './golden-part1.js';
export const BEDSIDESPEC = [
  { id: 'anion-gap', name: 'Anion gap', category: 'Bedside calculations', tier: 1,
    purpose: 'Metabolic acidosis workup (App A Row 2).',
    formula: 'AG = Na - (Cl + HCO3); corrected AG = AG + 2.5 x (4 - albumin)',
    engine: 'equation', citation: 'App A Row 2',
    inputs: [num('na','Sodium','mEq/L'),num('cl','Chloride','mEq/L'),num('hco3','Bicarbonate','mEq/L'),num('albumin','Albumin (optional)','g/dL',{required:false})],
    bands: [{ range: '8-12', label: 'Normal AG', meaning: 'Reference interval.' },{ range: '>12', label: 'High AG', meaning: 'High-AG metabolic acidosis workup.' }],
    compute: 'anion-gap' },
  { id: 'corrected-calcium', name: 'Corrected calcium', category: 'Bedside calculations', tier: 1,
    purpose: 'Hypo/hypercalcemia assessment (App A Row 4).', formula: 'CorrCa = Ca + 0.8 x (4 - albumin)',
    engine: 'equation', citation: 'App A Row 4',
    inputs: [num('ca','Measured calcium','mg/dL'),num('albumin','Albumin','g/dL')],
    bands: [{ range: '8.5-10.5', label: 'Normal', meaning: 'mg/dL reference interval.' }], compute: 'corrected-calcium' },
  { id: 'osmolality', name: 'Serum osmolality (calculated)', category: 'Bedside calculations', tier: 1,
    purpose: 'Calculated osmolality (App A Rows 5/137).', formula: '2xNa + glucose/18 + BUN/2.8',
    engine: 'equation', citation: 'App A Rows 5, 137',
    inputs: [num('na','Sodium','mEq/L'),num('glucose','Glucose','mg/dL'),num('bun','BUN','mg/dL')],
    bands: [{ range: '275-295', label: 'Normal', meaning: 'mOsm/kg reference interval.' }], compute: 'osmolality' },
  { id: 'meld', name: 'MELD', category: 'GI/Hepatology', tier: 1,
    purpose: '3-month liver waitlist mortality (App A Row 47 + E134).',
    formula: '3.78xln(bili) + 11.2xln(INR) + 9.57xln(Cr) + 6.43; floor 1.0; Cr cap 4.0 (dialysis=4); cap 40',
    engine: 'equation', citation: 'App A Row 47 / E134',
    inputs: [num('bili','Bilirubin','mg/dL'),num('inr','INR','ratio'),num('cr','Creatinine','mg/dL'),{ key:'dialysis', label:'Dialysis (2+ sessions/past week)', type:'boolean' }],
    bands: [{ range:'<9',label:'Low',meaning:'~2% 3-month mortality'},{ range:'10-19',label:'Moderate',meaning:'~6%'},{ range:'20-29',label:'High',meaning:'~20%'},{ range:'30-39',label:'Very high',meaning:'~53%'},{ range:'>=40',label:'Critical',meaning:'~71%' }],
    compute: 'meld' },
  { id: 'meld-na', name: 'MELD-Na', category: 'GI/Hepatology', tier: 1,
    purpose: 'MELD with hyponatremia correction (App A Row 48 + E133).',
    formula: 'MELD + 1.32x(137-Na) - 0.033xMELDx(137-Na); Na bounded 125-137',
    engine: 'equation', citation: 'App A Row 48 / E133',
    inputs: [num('meld','MELD','points'),num('na','Sodium','mEq/L')],
    bands: [{ range:'6-40',label:'Score',meaning:'Higher with hyponatremia.' }], compute: 'meld-na' },
  { id: 'child-pugh', name: 'Child-Pugh', category: 'GI/Hepatology', tier: 1,
    purpose: 'Cirrhosis severity (App A Row 43).', formula: 'Bilirubin + albumin + INR + ascites + encephalopathy (1-3 each); total 5-15',
    engine: 'points-sum', citation: 'App A Row 43',
    inputs: [
      sel('bili','Bilirubin',[['b1','<2 mg/dL',1],['b2','2-3 mg/dL',2],['b3','>3 mg/dL',3]]),
      sel('alb','Albumin',[['a1','>3.5 g/dL',1],['a2','2.8-3.5 g/dL',2],['a3','<2.8 g/dL',3]]),
      sel('inr','INR',[['i1','<1.7',1],['i2','1.7-2.3',2],['i3','>2.3',3]]),
      sel('asc','Ascites',[['n','None',1],['m','Mild',2],['s','Moderate-severe',3]]),
      sel('enc','Encephalopathy',[['n','None',1],['m','Grade I-II',2],['s','Grade III-IV',3]])],
    bands: [{ range:'5-6',label:'Class A',meaning:'Well-compensated.'},{ range:'7-9',label:'Class B',meaning:'Significant compromise.'},{ range:'10-15',label:'Class C',meaning:'Decompensated.'}] },
  { id: 'qtc', name: 'QTc (4 formulas)', category: 'Cardiovascular', tier: 1,
    purpose: 'ECG QT correction (App A Row 24).', formula: 'Bazett QT/sqrt(RR); Fridericia QT/cbrt(RR); Hodges QT+1.75(HR-60); Framingham QT+0.154(1-RR)',
    engine: 'equation', citation: 'App A Row 24',
    inputs: [num('qt','QT interval','ms'),num('hr','Heart rate','bpm')],
    bands: [{ range:'<450/470',label:'Normal',meaning:'Men <450 ms, women <470 ms.'},{ range:'>=500',label:'High',meaning:'Markedly prolonged; verify clinically.'}],
    compute: 'qtc' },
];
