import { sel, yn, num } from './golden-part1.js';
export const REST2SPEC = [
  { id: 'feverpain', name: 'FeverPAIN', category: 'Respiratory', tier: 1,
    purpose: 'Strep pharyngitis antibiotic guide (App B Row 163; max 5).',
    formula: 'Fever+Purulent+Attend<=3d+Inflamed+NoCough; 0-5',
    engine: 'points-sum', citation: 'App B Row 163',
    inputs: [yn('fev','Fever past 24h',1),yn('pur','Purulent exudate',1),yn('att','Attend within 3 days',1),yn('inf','Severely inflamed tonsils',1),yn('noc','No cough or coryza',1)],
    bands: [{ range:'0-1',label:'Low',meaning:'Strep A 13-18%. No antibiotic.'},{ range:'2-3',label:'Moderate',meaning:'34-38%. Delayed prescription.'},{ range:'4-5',label:'High',meaning:'62-65%. Immediate antibiotic.'}] },
  { id: 'smart-cop', name: 'SMART-COP', category: 'Respiratory', tier: 2,
    purpose: 'IRVS need in CAP (App B Row 251; max 12).',
    formula: 'SBP<90(2)+Multilobar(1)+Alb<3.5(1)+RR(1)+HR>=125(1)+Confusion(2)+Oxygen(2)+pH<7.35(2); 0-12',
    engine: 'points-sum', citation: 'App B Row 251',
    inputs: [yn('sbp','Systolic BP <90',2),yn('multi','Multilobar CXR',1),yn('alb','Albumin <3.5',1),yn('rr','RR high for age',1),yn('hr','HR >=125',1),yn('conf','New confusion',2),yn('oxy','Poor oxygenation',2),yn('ph','Arterial pH <7.35',2)],
    bands: [{ range:'0-2',label:'Low',meaning:'IRVS <=3%.'},{ range:'3-4',label:'Moderate',meaning:'IRVS 9-12%.'},{ range:'5-6',label:'High',meaning:'IRVS 26-35%.'},{ range:'>=7',label:'Very high',meaning:'IRVS >53%.'}] },
  { id: 'ariscat', name: 'ARISCAT', category: 'Surgery/Perioperative', tier: 2,
    purpose: 'Postop pulmonary complications (App B Row 257; max 123).',
    formula: 'Age(0/3/16)+SpO2(0/8/24)+RespInf(17)+Anemia(11)+Incision(0/15/24)+Duration(0/10/16)+Emergency(8); 0-123',
    engine: 'points-sum', citation: 'App B Row 257',
    inputs: [sel('age','Age',[['a','<=50',0],['b','51-80',3],['c','>80',16]]),
      sel('spo2','Preop SpO2',[['hi','>=96%',0],['mid','91-95%',8],['lo','<=90%',24]]),
      yn('inf','Respiratory infection last month',17),yn('ane','Anemia Hb<=10',11),
      sel('inc','Incision',[['per','Peripheral',0],['abd','Upper abdominal',15],['tho','Intrathoracic',24]]),
      sel('dur','Duration',[['s','<=2h',0],['m','2-3h',10],['l','>3h',16]]),yn('em','Emergency',8)],
    bands: [{ range:'0-26',label:'Low',meaning:'PPC <4%.'},{ range:'27-44',label:'Intermediate',meaning:'PPC 10-15%.'},{ range:'>=45',label:'High',meaning:'PPC 25-40%.'}] },
  { id: 'mpi', name: 'Mannheim Peritonitis Index', category: 'Surgery/Perioperative', tier: 2,
    purpose: 'Peritonitis mortality (App B Row 259; max 47).',
    formula: 'Age>50(5)+Female(5)+OrganFail(7)+Malignancy(4)+Dur>24h(4)+Diffuse(6)+Colon(4)+Exudate(0/6/12)',
    engine: 'points-sum', citation: 'App B Row 259',
    inputs: [yn('age','Age >50',5),yn('fem','Female',5),yn('of','Organ failure',7),yn('mal','Malignancy cause',4),yn('dur','Peritonitis >24h',4),yn('dif','Diffuse extent',6),yn('col','Colonic origin',4),
      sel('ex','Exudate',[['clear','Clear',0],['cloud','Cloudy/bloody',6],['faec','Faecal',12]])],
    bands: [{ range:'<21',label:'Low',meaning:'Mortality ~2.3%.'},{ range:'21-29',label:'Moderate',meaning:'~22.5%.'},{ range:'>=29',label:'High',meaning:'~59.1%.'}] },
];
