import { sel, yn, num } from './golden-part1.js';
export const CARDIOSPEC = [
  { id: 'cha2ds2-vasc', name: 'CHA2DS2-VASc', category: 'Cardiovascular', tier: 1,
    purpose: 'Stroke risk in AF (App A Row 15 + E014).', formula: 'CHF(1)+HTN(1)+Age>=75(2)+DM(1)+Stroke(2)+Vascular(1)+Age65-74(1)+Female(1); 0-9',
    engine: 'points-sum', citation: 'App A Row 15 / E014',
    inputs: [yn('chf','Congestive heart failure',1),yn('htn','Hypertension',1),
      sel('age','Age',[['lt65','<65 years',0],['a65','65-74 years',1],['a75','>=75 years',2]],'age'),
      yn('dm','Diabetes mellitus',1),yn('stroke','Stroke/TIA/thromboembolism',2),yn('vasc','Vascular disease',1),yn('female','Female sex',1)],
    bands: [{ range:'0 (M)/1 (F)',label:'Low',meaning:'OAC generally not recommended.'},{ range:'1 (M)/2 (F)',label:'Low-moderate',meaning:'Consider OAC.'},{ range:'>=2 (M)/>=3 (F)',label:'High',meaning:'OAC recommended.'}] },
  { id: 'atria', name: 'ATRIA stroke', category: 'Cardiovascular', tier: 1,
    purpose: 'AF stroke risk (App B Row 139 correction).', formula: 'CHF(1)+HTN(1)+DM(1)+Stroke(6)+Age65-74(2)+Age>=75(3)+Female(1); 0-13',
    engine: 'points-sum', citation: 'App B Row 139',
    inputs: [yn('chf','CHF',1),yn('htn','Hypertension',1),yn('dm','Diabetes',1),yn('stroke','Prior ischemic stroke/TIA',6),
      sel('age','Age',[['lt65','<65 years',0],['a65','65-74 years',2],['a75','>=75 years',3]],'age'),yn('female','Female sex',1)],
    bands: [{ range:'0-3',label:'Low',meaning:'Annual stroke ~0.6-1.4%.'},{ range:'4-5',label:'Intermediate',meaning:'~2.2-2.7%.'},{ range:'>=6',label:'High',meaning:'~3.7-14.2%.'}] },
  { id: 'hatch', name: 'HATCH', category: 'Cardiovascular', tier: 1,
    purpose: 'AF progression risk (App B Row 274; max 7).', formula: 'HTN(1)+Age>=75(1)+Stroke/TIA(2)+COPD(1)+HF(2); 0-7',
    engine: 'points-sum', citation: 'App B Row 274',
    inputs: [yn('htn','Hypertension',1),yn('age','Age >=75',1),yn('tia','TIA or stroke',2),yn('copd','COPD',1),yn('hf','Heart failure',2)],
    bands: [{ range:'0-4',label:'Lower',meaning:'Lower progression risk.'},{ range:'>=5',label:'High',meaning:'>50% progression to persistent AF within 1 year.'}] },
  { id: 'wells-dvt', name: 'Wells DVT', category: 'VTE prophylaxis', tier: 1,
    purpose: 'DVT pretest probability (App B Row 134; >=2 = likely).', formula: '9x(+1) + alternative diagnosis(-2); -2 to +8',
    engine: 'points-sum', citation: 'App B Row 134',
    inputs: [yn('ca','Active cancer',1),yn('par','Paralysis/paresis/immobilization',1),yn('bed','Bedridden >3d / surgery <12wk',1),yn('tend','Deep-vein tenderness',1),yn('swell','Entire leg swollen',1),yn('calf','Calf swelling >=3cm',1),yn('edema','Pitting edema (symptomatic leg)',1),yn('veins','Collateral superficial veins',1),yn('prev','Previously documented DVT',1),yn('alt','Alternative diagnosis >= as likely',-2)],
    bands: [{ range:'<=1',label:'DVT unlikely',meaning:'~5%.'},{ range:'>=2',label:'DVT likely',meaning:'~17-53%.'}] },
  { id: 'padua', name: 'Padua', category: 'VTE prophylaxis', tier: 1,
    purpose: 'VTE risk in medical inpatients (App B Row 133; max 20).', formula: 'Cancer(3)+prevVTE(3)+immobility(3)+thrombophilia(3)+trauma/surgery(2)+7x1pt items; 0-20',
    engine: 'points-sum', citation: 'App B Row 133',
    inputs: [yn('ca','Active cancer',3),yn('prev','Previous VTE',3),yn('mob','Reduced mobility >=3 days',3),yn('thromb','Known thrombophilia',3),yn('trauma','Recent trauma/surgery',2),yn('age','Age >=70',1),yn('hf','Heart/respiratory failure',1),yn('mi','Acute MI/stroke',1),yn('inf','Acute infection/rheumatologic',1),yn('ob','Obesity BMI>=30',1),yn('horm','Hormonal treatment',1)],
    bands: [{ range:'<4',label:'Low',meaning:'VTE ~0.3%.'},{ range:'>=4',label:'High',meaning:'VTE ~11%.'}] },
  { id: 'improve', name: 'IMPROVE VTE', category: 'VTE prophylaxis', tier: 2,
    purpose: 'VTE risk in medical inpatients (App B Row 272).', formula: 'prevVTE(3)+thrombophilia(2)+paralysis(2)+immobility(1)+cancer(2)+age60-74(1)/>=75(2)+ICU(1)+CVC(1)+varicose(1)+infection(1)+female(1)+hormonal(1)',
    engine: 'points-sum', citation: 'App B Row 272',
    inputs: [yn('prev','Previous VTE',3),yn('thr','Known thrombophilia',2),yn('par','Lower-limb paralysis/paresis',2),yn('imm','Immobilization >=1 week',1),yn('ca','Active cancer <=3mo',2),sel('age','Age',[['y','<60',0],['m','60-74',1],['o','>=75',2]],'age'),yn('icu','ICU/CCU stay',1),yn('cvc','Central venous catheter',1),yn('var','Varicose veins',1),yn('inf','Acute infectious disease',1),yn('fem','Female sex',1),yn('hor','Hormonal therapy',1)],
    bands: [{ range:'0-1',label:'Low',meaning:'VTE ~0.4%.'},{ range:'2-3',label:'Moderate',meaning:'~1.3-1.6%.'},{ range:'>=4',label:'High',meaning:'~3.6-5.7%.'}] },
  { id: 'pesi', name: 'PESI (full)', category: 'Respiratory', tier: 1,
    purpose: 'PE mortality classes (App B Row 252).', formula: 'Age(yrs)+Male(10)+Cancer(30)+HF(10)+Lung(10)+HR>=110(20)+SBP<100(30)+RR>=30(20)+T<36(20)+AMS(60)+SpO2<90(20)',
    engine: 'points-sum', citation: 'App B Row 252',
    inputs: [num('age','Age (years)','years'),yn('male','Male sex',10),yn('ca','Cancer',30),yn('hf','Heart failure',10),yn('lung','Chronic lung disease',10),yn('hr','HR >=110',20),yn('sbp','SBP <100',30),yn('rr','RR >=30',20),yn('t','Temperature <36C',20),yn('ams','Altered mental status',60),yn('spo2','SpO2 <90%',20)],
    bands: [{ range:'<=65',label:'Class I',meaning:'Mortality 0-1.6%.'},{ range:'66-85',label:'Class II',meaning:'1.7-3.5%.'},{ range:'86-105',label:'Class III',meaning:'3.2-7.1%.'},{ range:'106-125',label:'Class IV',meaning:'4.0-11.4%.'},{ range:'>125',label:'Class V',meaning:'10.0-24.5%.'}] },
  { id: 'spesi', name: 'sPESI', category: 'Respiratory', tier: 1,
    purpose: 'Simplified PE mortality (App B Row 252).', formula: '6x1pt items; 0-6; >=1 = high risk',
    engine: 'points-sum', citation: 'App B Row 252',
    inputs: [yn('age','Age >80',1),yn('ca','Cancer',1),yn('cp','Chronic cardiopulmonary disease',1),yn('hr','HR >=110',1),yn('sbp','SBP <100',1),yn('spo2','SpO2 <90%',1)],
    bands: [{ range:'0',label:'Low',meaning:'30-day mortality ~1.0%.'},{ range:'>=1',label:'High',meaning:'~10.9%.'}] },
  { id: 'geneva', name: 'Revised Geneva (simplified)', category: 'Respiratory', tier: 1,
    purpose: 'PE probability (App B Row 115; max 10).', formula: 'Age>65, prev DVT/PE, surgery/fracture, cancer, limb pain, hemoptysis, HR75-94(1)/>=95(2), palpation+edema; 0-10',
    engine: 'points-sum', citation: 'App B Row 115',
    inputs: [yn('age','Age >65',1),yn('prev','Previous DVT/PE',1),yn('surg','Surgery/fracture <1 month',1),yn('ca','Active malignancy',1),yn('pain','Unilateral limb pain',1),yn('hem','Hemoptysis',1),sel('hr','Heart rate',[['n','<75 bpm',0],['m','75-94 bpm',1],['h','>=95 bpm',2]],'hr'),yn('palp','Palpation pain + unilateral edema',1)],
    bands: [{ range:'0-1',label:'Low',meaning:'PE ~8-10%.'},{ range:'2-5',label:'Intermediate',meaning:'~23-28%.'},{ range:'>=6',label:'High',meaning:'~74%.'}] },
  { id: 'perc', name: 'PERC', category: 'Respiratory', tier: 1,
    purpose: 'PE exclusion - all 8 must be negative (App B Row 164).', formula: 'Age<50, HR<100, SpO2>94%, no hemoptysis/estrogen/prior VTE/leg swelling/surgery-trauma',
    engine: 'algorithm', citation: 'App B Row 164',
    inputs: [yn('age','Age <50',0),yn('hr','HR <100',0),yn('spo2','SpO2 >94% RA',0),yn('hem','Hemoptysis',1),yn('est','Estrogen use',1),yn('prev','Prior DVT/PE',1),yn('leg','Unilateral leg swelling',1),yn('surg','Surgery/trauma <4wk',1)],
    bands: [{ range:'PERC-negative',label:'PE excluded',meaning:'All 8 negative.'},{ range:'PERC-positive',label:'Cannot exclude',meaning:'Proceed to testing.'}],
    compute: 'perc' },
];
