const pilot={
 'Anion gap':{formula:'Na − (Cl + HCO₃)',fields:['Sodium','Chloride','Bicarbonate'],compute:v=>v[0]-(v[1]+v[2])},
 'MAP':{formula:'DBP + (SBP − DBP) / 3',fields:['Systolic BP','Diastolic BP'],compute:v=>Math.round(v[1]+(v[0]-v[1])/3)},
 'CHA2DS2-VASc':{formula:'CHF + HTN + Age + Diabetes + Stroke/TIA + Vascular disease + Sex',fields:[],compute:null},
 'HEART':{formula:'History + ECG + Age + Risk factors + Troponin',fields:[],compute:null},
 'qSOFA':{formula:'RR ≥22 + SBP ≤100 + altered mentation',fields:[],compute:null},
 'CURB-65':{formula:'Confusion + Urea + RR ≥30 + low BP + Age ≥65',fields:[],compute:null},
 'Glasgow Coma Scale (GCS)':{formula:'Eye + Verbal + Motor',fields:[],compute:null},
 'MELD':{formula:'3.78 ln(bilirubin) + 11.2 ln(INR) + 9.57 ln(creatinine) + 6.43',fields:[],compute:null}
};
const state={screen:'home',query:'',category:'All',tools:[],saved:JSON.parse(localStorage.getItem('clinicalc-web-saved')||'[]')};
const app=document.querySelector('#app');
function load(){fetch('../%23%20Comprehensive%20Medical%20Scoring%20Systems').then(r=>r.text()).then(source=>{const names=[...source.matchAll(/^\*\*([^*]+)\*\*/gm)].map(m=>m[1].trim()).filter((x,i,a)=>a.findIndex(y=>y.toLowerCase()===x.toLowerCase())===i).map(raw=>{const name=raw.split(' — ')[0].trim();return{name,category:categoryAt(source,raw),summary:raw.split(' — ')[1]||'Clinical scoring system',ready:Boolean(pilot[name])}});state.tools=names.filter(t=>t.name.length>2);render()}).catch(()=>{state.tools=Object.keys(pilot).map(name=>({name,category:'Pilot tools',summary:'Source catalog unavailable in preview',ready:true}));render()})}
function categoryAt(source,raw){const before=source.slice(0,source.indexOf(`**${raw}**`));const heads=[...before.matchAll(/^### (.+)$/gm)];return heads.length?heads.at(-1)[1].trim():'Clinical tools'}
function card(t){return`<article class="tool" data-name="${esc(t.name)}"><div class="tool-icon">${t.ready?'✓':'i'}</div><h3>${esc(t.name)}</h3><p>${esc(t.summary)}</p><div class="tool-foot"><span>${esc(t.category)}</span><span class="tag ${t.ready?'':'reference'}">${t.ready?'Calculator':'Reference'}</span></div></article>`}
function esc(v){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function home(){const list=state.tools.filter(t=>t.ready).slice(0,8);return`<section class="hero"><div><div class="eyebrow">Clinical decision support · offline-first</div><h1>Clarity when the clinical moment is moving fast.</h1><p>A calm, traceable home for bedside scores, risk tools, and essential calculations.</p></div><label class="search"><span>⌕</span><input id="search" placeholder="Search ${state.tools.length||'300+'} tools" value="${esc(state.query)}"></label></section><section class="bento"><article class="main"><div class="meta">QUICK CALC · READY</div><h2>Start with a score</h2><p>Search the catalog or open one of the verified pilot tools.</p><div class="orb"></div></article><article class="peach"><div class="meta">CATALOG</div><h2>${state.tools.length||'300+'} tools indexed</h2><p>Source headings are deduplicated at runtime.</p></article><article class="gold"><div class="meta">SAFETY</div><h2>Traceable by design</h2><p>Formula, confidence, and reference status stay visible.</p></article></section><div class="section-head"><h2>Bedside essentials</h2><a data-screen="browse">Browse all →</a></div><section class="grid">${list.map(card).join('')}</section>`}
function browse(){const shown=state.tools.filter(t=>`${t.name} ${t.category} ${t.summary}`.toLowerCase().includes(state.query.toLowerCase()));return`<section class="page-head"><div><div class="eyebrow">The catalog</div><h1>Find your score.</h1></div><label class="search"><span>⌕</span><input id="search" placeholder="Search by name or acronym" value="${esc(state.query)}"></label></section><div class="filters"><button class="active">All tools</button><button>Calculators</button><button>Reference only</button></div><p style="color:var(--muted);font-size:12px">${shown.length} of ${state.tools.length} indexed tools</p><section class="grid">${shown.length?shown.map(card).join(''):'<div class="empty" style="grid-column:1/-1"><h2>No matches</h2><p>Try another search.</p></div>'}</section>`}
function saved(){const list=state.tools.filter(t=>state.saved.includes(t.name));return`<section class="page-head"><div><div class="eyebrow">Personal workspace</div><h1>Saved tools.</h1></div></section>${list.length?`<section class="grid">${list.map(card).join('')}</section>`:'<div class="empty"><h2>Nothing here yet</h2><p>Open a tool and save it for quick access.</p></div>'}`}
function detail(t){const p=pilot[t.name];return`<section class="detail"><article class="panel"><button class="back" data-screen="browse">← Back to catalog</button><div class="eyebrow" style="margin-top:25px">${esc(t.category)}</div><h1>${esc(t.name)}</h1><p>${esc(t.summary)}</p>${p?.compute?`<div class="fields">${p.fields.map((f,i)=>`<label>${f}<input type="number" data-input="${i}" placeholder="Enter value"></label>`).join('')}</div><div class="result"><label>Live result</label><strong id="result">—</strong><small>Verify against current local protocol.</small></div>`:`<div class="result"><label>${t.ready?'Calculator pilot':'Reference only'}</label><strong>${t.ready?'Ready to expand':'No computed output'}</strong><small>${t.ready?'This pilot has a traceable formula mapping.':'Published coefficients or a complete scoring table still need review.'}</small></div>`}</article><aside class="panel side"><div><h3>Formula</h3><code>${esc(p?.formula||'Published scoring table or external coefficient model required.')}</code></div><div><h3>Source status</h3><p>${t.ready?'Pilot formula mapped from the supplied catalog.':'Reference heading indexed from the supplied catalog. Computation is intentionally blocked until reviewed.'}</p></div><div><h3>Clinical disclaimer</h3><p>Decision support for qualified professionals. Verify every result against current guidance and use clinical judgment.</p></div></aside></section>`}
function render(){const active=state.tools.find(t=>t.name===state.screen);app.innerHTML=active?detail(active):state.screen==='browse'?browse():state.screen==='saved'?saved():home();bind()}
function bind(){document.querySelectorAll('[data-screen]').forEach(x=>x.onclick=()=>{state.screen=x.dataset.screen;render()});const input=document.querySelector('#search');if(input)input.oninput=e=>{state.query=e.target.value;state.screen='browse';render()};document.querySelectorAll('.tool').forEach(x=>x.onclick=()=>{state.screen=x.dataset.name;render()});document.querySelectorAll('[data-input]').forEach(x=>x.oninput=()=>{const p=pilot[state.screen],v=[...document.querySelectorAll('[data-input]')].map(i=>Number(i.value));if(v.every(Number.isFinite))document.querySelector('#result').textContent=p.compute(v)});}
document.querySelector('#theme').onclick=()=>document.body.classList.toggle('dark');load();